feat: make openlane version configurable

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,12 +15,22 @@ inputs:
     default: 'tt07'
     required: false
     type: string
+  flow:
+    description: 'Flow used for hardening the chip'
+    default: 'openlane1'
+    required: false
+    type: choice
+    options:
+      - openlane1
+      - openlane2
 
 runs:
   using: 'composite'
   steps:
     - name: Set up environment variables
       shell: bash
+      env:
+        FLOW: ${{ inputs.flow }}
       run: |
         # REMINDER: When updating the OpenLane version do not forget to change the PDKs used for
         #           other actions in this repository precheck/action.yml, gl_test/action.yml,
@@ -30,9 +40,21 @@ runs:
         OPENLANE_TAG=2024.04.22
         OPENLANE_IMAGE_NAME=efabless/openlane:2024.04.22
         OPENLANE_ROOT=/home/runner/openlane
+        OPENLANE2_TAG=2.0.7
         PDK_ROOT=/home/runner/pdk
         PDK=sky130A
+        FLOW=$FLOW
         EOF
+        if [ "$FLOW" == "openlane1" ]
+        then
+          echo "FLOW_ARG=" >> $GITHUB_ENV
+        elif [ "$FLOW" == "openlane2" ]
+        then
+          echo "FLOW_ARG=--openlane2" >> $GITHUB_ENV
+        else
+          echo "Invalid flow '$FLOW'" >&2
+          exit 1
+        fi
 
     # Install packages for 'Render PNG from GDS' step:
     - name: Install prerequisites
@@ -60,18 +82,24 @@ runs:
 
     - name: Fetch verilog and build config
       shell: bash
-      run: ./tt/tt_tool.py --create-user-config
+      run: ./tt/tt_tool.py --create-user-config $FLOW_ARG
 
     - name: Install OpenLane
       shell: bash
       run: |
-        git clone --depth=1 --branch $OPENLANE_TAG https://github.com/The-OpenROAD-Project/OpenLane.git $OPENLANE_ROOT
-        cd $OPENLANE_ROOT
-        make
+        if [ "$FLOW" == "openlane1" ]
+        then
+          git clone --depth=1 --branch $OPENLANE_TAG https://github.com/The-OpenROAD-Project/OpenLane.git $OPENLANE_ROOT
+          cd $OPENLANE_ROOT
+          make
+        elif [ "$FLOW" == "openlane2" ]
+        then
+          pip install openlane==$OPENLANE2_TAG
+        fi
 
     - name: Make GDS with OpenLane
       shell: bash
-      run: ./tt/tt_tool.py --harden
+      run: ./tt/tt_tool.py --harden $FLOW_ARG
 
     - name: Show build files (for debugging)
       shell: bash
@@ -81,11 +109,26 @@ runs:
       if: always()
       shell: bash
       run: |
-        if [ -s runs/wokwi/logs/synthesis/linter.log ]; then
+        if [ "$FLOW" == "openlane1" ]
+        then
+          LINTER_LOG="runs/wokwi/logs/synthesis/linter.log"
+        elif [ "$FLOW" == "openlane2" ]
+        then
+          LINTER_LOG="runs/wokwi/*-verilator-lint/verilator-lint.log"
+        fi
+
+        LINTER_LOG=($LINTER_LOG)
+        LINTER_LOG="${LINTER_LOG[0]}"
+
+        echo "DEBUG LINTER_LOG *$LINTER_LOG*"
+        cat $LINTER_LOG
+        echo "END DEBUG"
+
+        if [ -s "$LINTER_LOG" ]; then
           set +e
-          count_error=$(egrep -i "^%Error"   runs/wokwi/logs/synthesis/linter.log | wc -l)
-          count_warn=$( egrep -i "^%Warning" runs/wokwi/logs/synthesis/linter.log | wc -l)
-          count_other=$(egrep -i "^%"        runs/wokwi/logs/synthesis/linter.log | egrep -v "%(Warning|Error)" | wc -l)
+          count_error=$(egrep -i "^%Error"   $LINTER_LOG | wc -l)
+          count_warn=$( egrep -i "^%Warning" $LINTER_LOG | wc -l)
+          count_other=$(egrep -i "^%"        $LINTER_LOG | egrep -v "%(Warning|Error)" | wc -l)
           set -e
 
           open=""
@@ -112,22 +155,22 @@ runs:
           echo "<summary><h1>Linter output&nbsp;&nbsp;<h4>${summary} ${icon}</h4></h1></summary>" >> $GITHUB_STEP_SUMMARY
           echo "<pre>" >> $GITHUB_STEP_SUMMARY
           # Print each line of the file preceeded by four spaces:
-          sed 's/^/    /' < runs/wokwi/logs/synthesis/linter.log >> $GITHUB_STEP_SUMMARY
+          sed 's/^/    /' < $LINTER_LOG >> $GITHUB_STEP_SUMMARY
           echo "</pre>" >> $GITHUB_STEP_SUMMARY
           echo "</details>" >> $GITHUB_STEP_SUMMARY
         fi
 
     - name: Yosys warnings
       shell: bash
-      run: ./tt/tt_tool.py --print-warnings >> $GITHUB_STEP_SUMMARY
+      run: ./tt/tt_tool.py --print-warnings $FLOW_ARG >> $GITHUB_STEP_SUMMARY
 
     - name: Routing summary
       shell: bash
-      run: ./tt/tt_tool.py --print-stats >> $GITHUB_STEP_SUMMARY
+      run: ./tt/tt_tool.py --print-stats $FLOW_ARG >> $GITHUB_STEP_SUMMARY
 
     - name: Cell usage summary
       shell: bash
-      run: ./tt/tt_tool.py --print-cell-category >> $GITHUB_STEP_SUMMARY
+      run: ./tt/tt_tool.py --print-cell-category $FLOW_ARG >> $GITHUB_STEP_SUMMARY
 
     - name: Publish build logs
       if: success() || failure()
@@ -142,14 +185,26 @@ runs:
       shell: bash
       run: |
         mkdir -p tt_submission
-        TOP_MODULE=$(./tt/tt_tool.py --print-top-module)
-        cp runs/wokwi/results/final/commit_id.json tt_submission/
-        cp runs/wokwi/results/final/{gds,lef,spef}/${TOP_MODULE}.* tt_submission/
-        cp runs/wokwi/results/final/verilog/gl/${TOP_MODULE}.v tt_submission/
-        cp runs/wokwi/{OPENLANE_VERSION,PDK_SOURCES,config.tcl} tt_submission/
         mkdir -p tt_submission/stats
-        cp runs/wokwi/reports/metrics.csv tt_submission/stats/metrics.csv
-        cp runs/wokwi/reports/synthesis/1-synthesis.AREA_0.stat.rpt tt_submission/stats/synthesis-stats.txt
+        if [ "$FLOW" == "openlane1" ]
+        then
+          TOP_MODULE=$(./tt/tt_tool.py --print-top-module)
+          cp runs/wokwi/results/final/commit_id.json tt_submission/
+          cp runs/wokwi/results/final/{gds,lef,spef}/${TOP_MODULE}.* tt_submission/
+          cp runs/wokwi/results/final/verilog/gl/${TOP_MODULE}.v tt_submission/
+          cp runs/wokwi/{OPENLANE_VERSION,PDK_SOURCES,config.tcl} tt_submission/
+          cp runs/wokwi/reports/metrics.csv tt_submission/stats/metrics.csv
+          cp runs/wokwi/reports/synthesis/1-synthesis.AREA_0.stat.rpt tt_submission/stats/synthesis-stats.txt
+        elif [ "$FLOW" == "openlane2" ]
+        then
+          TOP_MODULE=$(./tt/tt_tool.py --print-top-module --openlane2)
+          cp runs/wokwi/final/commit_id.json tt_submission/
+          cp runs/wokwi/final/{gds,lef,spef/*}/${TOP_MODULE}.* tt_submission/
+          cp runs/wokwi/final/pnl/${TOP_MODULE}.pnl.v tt_submission/${TOP_MODULE}.v
+          cp runs/wokwi/{OPENLANE_VERSION,PDK_SOURCES,resolved.json} tt_submission/
+          cp runs/wokwi/final/metrics.csv tt_submission/stats/metrics.csv
+          cp runs/wokwi/*-yosys-synthesis/reports/stat.log tt_submission/stats/synthesis-stats.txt
+        fi
 
     - name: Publish tt_submission artifact
       uses: actions/upload-artifact@v4
@@ -165,7 +220,7 @@ runs:
     # Create and store PNG...
     - name: Render PNG from GDS
       shell: bash
-      run: './tt/tt_tool.py --create-png 2>&1 || echo "WARNING: Failed to render PNG preview from GDS; error $?"'
+      run: './tt/tt_tool.py --create-png $FLOW_ARG 2>&1 || echo "WARNING: Failed to render PNG preview from GDS; error $?"'
 
     - name: Upload gds_render (png) artifact
       uses: actions/upload-artifact@v4
