feat: include additional logs in the GDS artifact

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,5 +1,5 @@
-name: 'Tiny Tapeout GDS Action'
-description: 'This action builds a GDS file from your Tiny Tapeout project'
+name: 'Tiny Tapeout GDS Action (OpenLane 2)'
+description: 'This action builds a GDS file from your Tiny Tapeout project using OpenLane 2'
 branding:
   color: purple
   icon: layers
@@ -11,10 +11,8 @@ runs:
       shell: bash
       run: |
         cat << EOF >> $GITHUB_ENV
-        OPENLANE_TAG=2023.09.11
-        OPENLANE_IMAGE_NAME=efabless/openlane:7e5a2e9fb274c0a100b4859a927adce7089455ff
-        OPENLANE_ROOT=/home/runner/openlane
-        PDK_ROOT=/home/runner/pdk
+        OPENLANE_TAG=2.0.0b13
+        OPENLANE_ROOT=$GITHUB_WORKSPACE/openlane
         PDK=sky130A
         EOF
 
@@ -26,7 +24,7 @@ runs:
         version: tt05 # I think naming a version builds a reusable packages cache for that name.
 
     - name: Checkout tt-support-tools repo
-      uses: actions/checkout@v3
+      uses: actions/checkout@v4
       with:
         repository: tinytapeout/tt-support-tools
         path: tt
@@ -46,16 +44,28 @@ runs:
       shell: bash
       run: ./tt/tt_tool.py --create-user-config
 
-    - name: Install OpenLane
+    - name: Checkout OpenLane 2 repo
+      uses: actions/checkout@v4
+      with:
+        repository: efabless/openlane2
+        path: ${{ env.OPENLANE_ROOT }}
+        ref: ${{ env.OPENLANE_TAG }}
+
+    - uses: cachix/install-nix-action@v20
+
+    - uses: cachix/cachix-action@v12
+      with:
+        name: openlane
+        extraPullNames: openlane
+
+    - name: Make GDS with OpenLane 2
       shell: bash
       run: |
-        git clone --depth=1 --branch $OPENLANE_TAG https://github.com/The-OpenROAD-Project/OpenLane.git $OPENLANE_ROOT
-        cd $OPENLANE_ROOT
-        make
-
-    - name: Make GDS with OpenLane
-      shell: bash
-      run: ./tt/tt_tool.py --harden
+        cat src/config.tcl src/user_config.tcl > src/config.combined.tcl
+        nix-shell $OPENLANE_ROOT/shell.nix --run "python -m openlane --run-tag wokwi src/config.combined.tcl"
+        mv src/runs runs
+        # The next command doesn't really harden, it only creates the required commit_id.json file:
+        ./tt/tt_tool.py --harden --openlane2
 
     - name: Show build files (for debugging)
       shell: bash
@@ -63,15 +73,16 @@ runs:
 
     - name: Yosys warnings
       shell: bash
-      run: ./tt/tt_tool.py --print-warnings >> $GITHUB_STEP_SUMMARY
+      run: ./tt/tt_tool.py --print-warnings --openlane2 >> $GITHUB_STEP_SUMMARY
 
     - name: Routing summary
       shell: bash
-      run: ./tt/tt_tool.py --print-stats >> $GITHUB_STEP_SUMMARY
+      run: echo Routing summary is not yet available for OpenLane 2 >> $GITHUB_STEP_SUMMARY
+      #run: ./tt/tt_tool.py --print-stats --openlane2 >> $GITHUB_STEP_SUMMARY
 
     - name: Cell usage summary
       shell: bash
-      run: ./tt/tt_tool.py --print-cell-category >> $GITHUB_STEP_SUMMARY
+      run: ./tt/tt_tool.py --print-cell-category --openlane2 >> $GITHUB_STEP_SUMMARY
 
     - name: Publish build logs
       if: success() || failure()
@@ -88,18 +99,17 @@ runs:
         name: GDS
         path: |
           src/*
-          runs/wokwi/results/final/*
-          runs/wokwi/reports/metrics.csv
-          runs/wokwi/reports/synthesis/1-synthesis*
-          runs/wokwi/OPENLANE_VERSION
-          runs/wokwi/PDK_SOURCES
-          runs/wokwi/config.tcl
+          runs/wokwi/final/*
+          runs/wokwi/05-yosys-synthesis/yosys-synthesis.log
+          runs/wokwi/05-yosys-synthesis/reports/stat.json
+          runs/wokwi/*.log
+          runs/wokwi/resolved.json
           LICENSE
 
     # Create and store PNG...
     - name: Render PNG from GDS
       shell: bash
-      run: './tt/tt_tool.py --create-png 2>&1 || echo "WARNING: Failed to render PNG preview from GDS; error $?"'
+      run: './tt/tt_tool.py --create-png --openlane2 2>&1 || echo "WARNING: Failed to render PNG preview from GDS; error $?"'
 
     - name: Upload gds_render (png) artifact
       uses: actions/upload-artifact@v3
